In [2]:
import numpy as np

# 1. Создайте массив из 10 элементов и каждый элемент умножьте на 2
a = np.arange(10)
print(a)
print(a * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [2]:
# создадим numpy массив со значениями 2,3 , 2.5
a = np.array([2, 3, 2.5])

a*72

array([144., 216., 180.])

In [3]:
b = np.array([120,150,190])
c = np.array([130,130,130])

(a*72) + b + c

array([394., 496., 500.])

In [4]:
a = np.array([4, 6])
b = np.array([-1, -2])

a+b

array([3, 4])

In [5]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [6]:
p = np.array([4, 5])
v = np.array([2, 1])
s = np.array([1, 0])
omega1 = 2
omega2 = -3
omega3 = 5
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([7, 7])

In [8]:
sdelal = np.array([3, 4, 5, 9])
prodal = np.array([1,5,3,6])
#s = np.array([1, 0])
omega1 = 200
omega2 = 400
#omega3 = 5
u = omega2*prodal - omega1*sdelal
u

array([-200, 1200,  200,  600])

In [10]:
a = np.array([4, 5, -1])
w = np.array([2, 0, 1, ])
np.dot(a, w)

7

In [3]:
this = np.array([3, 4, 5, 9])

# создадим массив sdvig, который будет являться массивом this со сдвигом на 1 элемент вправо
sdvig = np.roll(this, 1)

sdvig

array([9, 3, 4, 5])