In [ ]:
import numpy as np

In [ ]:
# как создать матрицу?

In [ ]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

In [ ]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

In [ ]:
# размер матрицы
np.shape(A)

In [ ]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

In [ ]:
# вектор-строка
np.reshape(x,(1,3))

In [ ]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

In [ ]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

In [ ]:
# создание специальных матриц

In [ ]:
# нулевая
np.zeros((2,3))

In [ ]:
# единичная
np.eye(3)

In [ ]:
# матрица единиц
np.ones((3,5))

In [ ]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

In [ ]:
# Шаровая
5*np.eye(3)

In [ ]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
B+A

In [ ]:
A-B

In [ ]:
2*A

In [ ]:
A.T

In [ ]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

In [ ]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

In [ ]:
x_col.T

In [ ]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

## Задания

In [1]:
# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [2]:
# транспонируем эти массивы, чтобы получить вектор-столбцы
Husband_Income=np.reshape(Husband_Income,(3,1))
Wife_Income=np.reshape(Wife_Income,(3,1))
Mother_In_Law_Income=np.reshape(Mother_In_Law_Income,(3,1))

Husband_Consumption=np.reshape(Husband_Consumption,(3,1))
Wife_Consumption=np.reshape(Wife_Consumption,(3,1))
Mother_In_Law_Consumption=np.reshape(Mother_In_Law_Consumption,(3,1))


In [3]:
# создаем матрицу доходов
Incomes=np.hstack((Husband_Income,Wife_Income,Mother_In_Law_Income))

Incomes

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [4]:
# создаем матрицу расходов
Consumptions=np.hstack((Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption))

Consumptions

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [9]:
Incomes_aftertax = Incomes*0.87
Incomes_aftertax[0]

array([ 87. , 130.5,  78.3])

In [10]:
P = Incomes_aftertax - Consumptions
P[2]

array([ 61.8, -26.9, -53. ])

In [15]:
A=np.array([[1,-1,2,4,0],[8,2,0,5,3],[0,1,2,1,2]])
B=np.array([[1,0,1,0],[0,0,2,-1],[1,0,1,1],[0,1,1,1],[1,1,0,-1]])

# умножим матрицу А на матрицу В

C=np.dot(A,B)

C

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [16]:
# создадим вектор-столбец
x1=np.array([1,3])
x2=np.array([-3,1])

# найдём тензорное произведение векторов x1 и x2
np.tensordot(x1,x2,axes=0)


array([[-3,  1],
       [-9,  3]])