In [18]:
import numpy as np

In [19]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [20]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [21]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [22]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]] 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
check OK


In [10]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [23]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [12]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [24]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [26]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

LinAlgError: Singular matrix

In [28]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

LinAlgError: Singular matrix

In [29]:
print('det(A1)):\n',np.linalg.det(A1))

det(A1)):
 -2.9999999999999996


In [30]:
print('det(A2)):\n',np.linalg.det(A2))

det(A2)):
 0.0


In [31]:
print('det(A3)):\n',np.linalg.det(A3))

det(A3)):
 0.0


In [ ]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

In [ ]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

In [32]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [33]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [34]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 2.0000000000000004


In [35]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


In [40]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
# найдём обратную матрицу
A_inv = np.linalg.inv(A)
A_inv
print(A_inv[1,0])

0.3750000000000005


In [41]:
# Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# построим матрицу из векторов
A = np.array([v1, v2, v3, v4]).T
print('Матрица A:\n',A)

Матрица A:
 [[ 9  2  4  3]
 [10  0  0 -4]
 [ 7  5  0  3]
 [ 7  1  4 -1]
 [ 9  4  1 -4]]


In [43]:
# найдём ранг матрицы A
print('Ранг матрицы A:\n',np.linalg.matrix_rank(A))

Ранг матрицы A:
 4


In [45]:
# найдём матрицу Грама
G = A.T@A
print('Матрица Грама:\n',G)


Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [47]:
# найдём определитель матрицы Грама
print('Определитель матрицы Грама:\n',np.linalg.det(G))


Определитель матрицы Грама:
 3716647.9999999995


In [48]:
# найдём обратную матрицу к матрице Грама
G_inv = np.linalg.inv(G)
print('Обратная к матрице Грама:\n',G_inv)


Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]


In [56]:

k = [10,11,8,8,10,200]
# находим среднее значение
k_mean = np.mean(k)
k_median = np.median(k)
print('Среднее значение:', k_mean)
print('Медиана:', k_median)




Среднее значение: 41.166666666666664
Медиана: 10.0


In [61]:
k=np.empty(5)
k[0]=1
k[1]=2
k[2]=3
k[3]=4
k[4]=5

# сдвинем все значения на 1 вправо
k_shift = np.roll(k, 1)
print('k_shift:', k_shift)

k_shift: [5. 1. 2. 3. 4.]


In [62]:
v1 = np.array([-1, 2, -7, 9])
v2 = np.array([2, 8, 2, -1])

#найдём скалярное произведение векторов
print('Скалярное произведение векторов:', v1@v2)

Скалярное произведение векторов: -9


In [63]:
A = np.array([[1, 1], [1, 2]])

# найдём матрицу Грама
G = A.T@A
print('Матрица Грама:\n',G)

Матрица Грама:
 [[2 3]
 [3 5]]


In [65]:
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])

# построим матрицу из векторов
A = np.array([v1, v2, v3]).T
print('Матрица A:\n',A)

# найдём ранг матрицы A
print('Ранг матрицы A:\n',np.linalg.matrix_rank(A))

Матрица A:
 [[ 2  3  8]
 [10  2 14]
 [-2 -2 -6]]
Ранг матрицы A:
 2


In [66]:
v1 = np.array([5, 1])
v2 = np.array([10, 2])

# построим матрицу из векторов
A = np.array([v1, v2]).T
print('Матрица A:\n',A)

# найдём ранг матрицы A
print('Ранг матрицы A:\n',np.linalg.matrix_rank(A))

Матрица A:
 [[ 5 10]
 [ 1  2]]
Ранг матрицы A:
 1


In [ ]:
# запишем СЛАУ в матричном виде 5w1 + w2 + 3w3 = 1
# 2w2 + 8w3 = 10
# 10w1 + 2w3 = 0
A = np.array([[5, 1, 3], [0, 2, 8], [10, 0, 2]])




In [70]:
A = np.array([[4, 7, 20], [5, 10, 30]])

# найдём ранг матрицы A
print('Ранг матрицы A:\n',np.linalg.matrix_rank(A))



Ранг матрицы A:
 2


In [71]:
A = np.array([[4, 7], [5, 10]])
B = np.array([20, 30])
# найдём обратную матрицу к матрице A
A_inv = np.linalg.inv(A)
print('Обратная к матрице A:\n',A_inv)

Обратная к матрице A:
 [[ 2.  -1.4]
 [-1.   0.8]]


In [72]:
A_inv@B

array([-2.,  4.])

In [73]:
A = np.array([[4, 7, -1], [-4, 2, 5],[0,9,4]])

# найдём ранг матрицы A
print('Ранг матрицы A:\n',np.linalg.matrix_rank(A))

Ранг матрицы A:
 2


In [92]:
A = np.array([[1, -5], [2, 1],[1,1]])
B = np.array([[1], [2], [2]])
l = np.array([[1, 1]])
# B = B.T

# найдём линейную комбинацию столбцов матрицы A (b с крышкой)
print('Линейная комбинация столбцов матрицы A:\n',A@l.T)

# вектор ошибок e = b - b с крышкой
e = B - A@l.T
print('Вектор ошибок:\n',e)



Линейная комбинация столбцов матрицы A:
 [[-4]
 [ 3]
 [ 2]]
Вектор ошибок:
 [[ 5]
 [-1]
 [ 0]]


### Задание 2.11

Найдите -оценку для коэффициентов ,  СЛАУ:

In [93]:
A = np.array([[1, 2], [-3, 1],[1,2],[1,-1]])
B = np.array([[1], [4], [5],[0]])
# вычислим матрицу Грама
G = A.T@A
print('Матрица Грама:\n',G)

Матрица Грама:
 [[12  0]
 [ 0 10]]


In [96]:
# вычислим обратную матрицу к матрице Грама
G_inv = np.linalg.inv(G)
print('Обратная к матрице Грама:\n',G_inv)

Обратная к матрице Грама:
 [[0.08333333 0.        ]
 [0.         0.1       ]]


In [97]:
# вычислим коэффициенты линейной комбинации 
l = G_inv@A.T@B
print('Коэффициенты линейной комбинации:\n',l)

Коэффициенты линейной комбинации:
 [[-0.5]
 [ 1.6]]


In [ ]:
# найдём вектор коэффициентов линейной комбинации
l = np.array([[1, 1]])



In [98]:
# найдём вектор ошибок
e = B - A@l
print('Вектор ошибок:\n',e)

Вектор ошибок:
 [[-1.7]
 [ 0.9]
 [ 2.3]
 [ 2.1]]


In [99]:
A = np.array([[1, 2], [3, 7]])
# найдём обратную матрицу к матрице A
A_inv = np.linalg.inv(A)
print('Обратная к матрице A:\n',A_inv)


Обратная к матрице A:
 [[ 7. -2.]
 [-3.  1.]]
